export const FETCH_ARTICLES_REQUEST = "FETCH_ARTICLES_REQUEST";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAILURE = "FETCH_ARTICLES_FAILURE";

export const CURRENT_ARTICLES_PAGE = "CURRENT_ARTICLES_PAGE";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const CLEAR_REGISTER_USER_DATA = "CLEAR_REGISTER_USER_DATA";

export const LOGIN_TO_ACCOUNT_REQUEST = "LOGIN_TO_ACCOUNT_REQUEST";
export const LOGIN_TO_ACCOUNT_SUCCESS = "LOGIN_TO_ACCOUNT_SUCCESS";
export const LOGIN_TO_ACCOUNT_FAILURE = "LOGIN_TO_ACCOUNT_FAILURE";
export const LOGIN_OUT = "LOGIN_OUT";
export const CLEAR_USER_LOGIN_ERROR = "CLEAR_USER_LOGIN_ERROR";

export const CHANGE_USER_DATA_REQUEST = "CHANGE_USER_DATA_REQUEST";
export const CHANGE_USER_DATA_SUCCESS = "CHANGE_USER_DATA_SUCCESS";
export const CHANGE_USER_DATA_FAILURE = "CHANGE_USER_DATA_FAILURE";
export const CLEAR_CHANGE_USER_DATA_ERROR = "CLEAR_CHANGE_USER_DATA_ERROR";

export const CREATE_ARTICLES_REQUEST = "CREATE_ARTICLES_REQUEST";
export const CREATE_ARTICLES_SUCCESS = "CREATE_ARTICLES_SUCCESS";
export const CREATE_ARTICLES_FAILURE = "CREATE_ARTICLES_FAILURE";

export const ARTICLE_DELETE_SUCCESS = "ARTICLE_DELETE_SUCCESS";

export const LIKE_ARTICLE_REQUEST = "LIKE_ARTICLE_REQUEST";
export const LIKE_ARTICLE_SUCCESS = "LIKE_ARTICLE_SUCCESS";
export const LIKE_ARTICLE_FAILURE = "LIKE_ARTICLE_FAILURE";

export const UNLIKE_ARTICLE_REQUEST = "UNLIKE_ARTICLE_REQUEST";
export const UNLIKE_ARTICLE_SUCCESS = "UNLIKE_ARTICLE_SUCCESS";
export const UNLIKE_ARTICLE_FAILURE = "UNLIKE_ARTICLE_FAILURE";
