export const FETCH_ARTICLES_REQUEST = "FETCH_ARTICLES_REQUEST";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAILURE = "FETCH_ARTICLES_FAILURE";

export const CURRENT_ARTICLES_PAGE = "CURRENT_ARTICLES_PAGE";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const CLEAR_REGISTER_USER_DATA = "CLEAR_REGISTER_USER_DATA";

export const LOGIN_TO_ACCOUNT_REQUEST = "LOGIN_TO_ACCOUNT_REQUEST";
export const LOGIN_TO_ACCOUNT_SUCCESS = "LOGIN_TO_ACCOUNT_SUCCESS";
export const LOGIN_TO_ACCOUNT_FAILURE = "LOGIN_TO_ACCOUNT_FAILURE";
export const LOGIN_OUT = "LOGIN_OUT";
